FROM apache/airflow:2.9.3

# Usar directamente el usuario airflow para instalar paquetes
USER airflow

RUN pip install --no-cache-dir \
    yfinance \
    sqlalchemy \
    psycopg2-binary \
    pyarrow